rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    max-spaces-after: 1
  comments:
    min-spaces-from-content: 1
  comments-indentation: {}
  document-end: disable
  document-start: disable
  empty-lines:
    max: 2
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: 2
  key-duplicates: enable
  line-length:
    max: 120
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  trailing-spaces: enable
  truthy: disable
